In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('online_retail.csv')
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [4]:
df.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [5]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [6]:
df= df.dropna(subset=['Customer ID'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 824364 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      824364 non-null  object
 1   StockCode    824364 non-null  object
 2   Description  824364 non-null  object
 3   Quantity     824364 non-null  int64
 4   InvoiceDate  824364 non-null  object
 5   Price        824364 non-null  float64
 6   Customer ID  824364 non-null  float64
 7   Country      824364 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 56.6+ MB

In [8]:
df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [9]:
df= df[df['Quantity']>0]
df= df[~df['Invoice'].astype(str).str.startswith('C')]

In [10]:
df= df[df['Price']>0]

In [11]:
df= df.copy()

In [12]:
df['InvoiceDate']= pd.to_datetime(df['InvoiceDate'])

In [13]:
df.duplicated().sum()

np.int64(26124)

In [14]:
df[df.duplicated()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067136,581538,22068,BLACK PIRATE TREASURE CHEST,1,2011-12-09 11:34:00,0.39,14446.0,United Kingdom
1067150,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,2011-12-09 11:34:00,2.49,14446.0,United Kingdom
1067153,581538,22992,REVOLVER WOODEN RULER,1,2011-12-09 11:34:00,1.95,14446.0,United Kingdom
1067160,581538,22694,WICKER STAR,1,2011-12-09 11:34:00,2.10,14446.0,United Kingdom
1067162,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom

In [15]:
df= df.drop_duplicates()

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 779425 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  object
 1   StockCode    779425 non-null  object
 2   Description  779425 non-null  object
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  datetime64[ns]
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  float64
 7   Country      779425 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 53.5+ MB

In [17]:
df['Revenue']= df['Quantity'] * df['Price']

In [18]:
df['Year']= df['InvoiceDate'].dt.year
df['Month']= df['InvoiceDate'].dt.month
df['MonthYear']= df['InvoiceDate'].dt.to_period('M')

In [19]:
customer_orders= df.groupby('Customer ID')['Invoice'].nunique().reset_index()
customer_orders.columns= ['Customer ID', 'OrderCount']

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 779425 entries, 0 to 1067370
Data columns (total 12 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  object
 1   StockCode    779425 non-null  object
 2   Description  779425 non-null  object
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  datetime64[ns]
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  float64
 7   Country      779425 non-null  object
 8   Revenue      779425 non-null  float64
 9   Year         779425 non-null  int32
 10  Month        779425 non-null  int32
 11  MonthYear    779425 non-null  period[M]
dtypes: datetime64[ns](1), float64(3), int32(2), int64(1), object(4), period[M](1)
memory usage: 71.4+ MB

In [21]:
customer_orders['CustomerType']= customer_orders['OrderCount'].apply(
    lambda x: 'Repeat' if x>1 else 'New'
)
df= df.merge(customer_orders[['Customer ID', 'CustomerType']], on= 'Customer ID')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 779425 entries, 0 to 779424
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Invoice       779425 non-null  object
 1   StockCode     779425 non-null  object
 2   Description   779425 non-null  object
 3   Quantity      779425 non-null  int64
 4   InvoiceDate   779425 non-null  datetime64[ns]
 5   Price         779425 non-null  float64
 6   Customer ID   779425 non-null  float64
 7   Country       779425 non-null  object
 8   Revenue       779425 non-null  float64
 9   Year          779425 non-null  int32
 10  Month         779425 non-null  int32
 11  MonthYear     779425 non-null  period[M]
 12  CustomerType  779425 non-null  object
dtypes: datetime64[ns](1), float64(3), int32(2), int64(1), object(5), period[M](1)
memory usage: 71.4+ MB

In [23]:
df.shape

(779425, 13)

In [24]:
df['CustomerType'].value_counts()

CustomerType
Repeat    745119
New        34306
Name: count, dtype: int64

In [25]:
df['Revenue'].sum()

np.float64(17374804.268000003)

In [26]:
customer_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5878 entries, 0 to 5877
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Customer ID   5878 non-null   float64
 1   OrderCount    5878 non-null   int64
 2   CustomerType  5878 non-null   object
dtypes: float64(1), int64(1), object(1)
memory usage: 137.9+ KB

In [27]:
df['MonthYear']= df['MonthYear'].astype(str)

In [28]:
df.rename(columns={'Customer ID':'CustomerID'}, inplace= True)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 779425 entries, 0 to 779424
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Invoice       779425 non-null  object
 1   StockCode     779425 non-null  object
 2   Description   779425 non-null  object
 3   Quantity      779425 non-null  int64
 4   InvoiceDate   779425 non-null  datetime64[ns]
 5   Price         779425 non-null  float64
 6   CustomerID    779425 non-null  float64
 7   Country       779425 non-null  object
 8   Revenue       779425 non-null  float64
 9   Year          779425 non-null  int32
 10  Month         779425 non-null  int32
 11  MonthYear     779425 non-null  object
 12  CustomerType  779425 non-null  object
dtypes: datetime64[ns](1), float64(3), int32(2), int64(1), object(6)
memory usage: 71.4+ MB

In [30]:
df.to_csv("retail_clean.csv", index=False)